listen_addresses = '*'
max_connections = 100
shared_buffers = 128MB
work_mem = 8MB
shared_preload_libraries = 'pg_cron'
pg_cron.database_name = 'postgres'
log_destination = 'stderr'
logging_collector = off

cron.use_background_workers = on
max_worker_processes = 20
